// <auto-generated />
using System;
using ComedyEvents.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace ComedyEvents.Migrations
{
    [DbContext(typeof(EventContext))]
    [Migration("20190521025631_InitialMigration")]
    partial class InitialMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.0-rtm-35687")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("ComedyEvents.Models.Comedian", b =>
                {
                    b.Property<int>("ComedianId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ContactPhone");

                    b.Property<string>("FirstName");

                    b.Property<string>("LastName");

                    b.HasKey("ComedianId");

                    b.ToTable("Comedians");

                    b.HasData(
                        new
                        {
                            ComedianId = 1,
                            ContactPhone = "111-222-3333",
                            FirstName = "Pavol",
                            LastName = "Almasi"
                        },
                        new
                        {
                            ComedianId = 2,
                            ContactPhone = "444-555-6666",
                            FirstName = "Robin",
                            LastName = "Williams"
                        });
                });

            modelBuilder.Entity("ComedyEvents.Models.Event", b =>
                {
                    b.Property<int>("EventId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("EventDate");

                    b.Property<string>("EventName");

                    b.Property<int?>("VenueId");

                    b.HasKey("EventId");

                    b.HasIndex("VenueId");

                    b.ToTable("Events");

                    b.HasData(
                        new
                        {
                            EventId = 1,
                            EventDate = new DateTime(2019, 5, 19, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EventName = "Funny Comedy Night",
                            VenueId = 1
                        });
                });

            modelBuilder.Entity("ComedyEvents.Models.Gig", b =>
                {
                    b.Property<int>("GigId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("ComedianId");

                    b.Property<int?>("EventId");

                    b.Property<string>("GigHeadline");

                    b.Property<int>("GigLengthInMinutes");

                    b.HasKey("GigId");

                    b.HasIndex("ComedianId");

                    b.HasIndex("EventId");

                    b.ToTable("Gigs");

                    b.HasData(
                        new
                        {
                            GigId = 1,
                            ComedianId = 1,
                            EventId = 1,
                            GigHeadline = "Pavols Funny Show",
                            GigLengthInMinutes = 60
                        },
                        new
                        {
                            GigId = 2,
                            ComedianId = 2,
                            EventId = 1,
                            GigHeadline = "Lifetime Of Fun",
                            GigLengthInMinutes = 45
                        });
                });

            modelBuilder.Entity("ComedyEvents.Models.Venue", b =>
                {
                    b.Property<int>("VenueId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("City");

                    b.Property<int>("Seating");

                    b.Property<bool>("ServesAlcohol");

                    b.Property<string>("State");

                    b.Property<string>("Street");

                    b.Property<string>("VenueName");

                    b.Property<string>("ZipCode");

                    b.HasKey("VenueId");

                    b.ToTable("Venues");

                    b.HasData(
                        new
                        {
                            VenueId = 1,
                            City = "Wilkes Barre",
                            Seating = 125,
                            ServesAlcohol = true,
                            State = "PA",
                            Street = "123 Main Street",
                            VenueName = "Mohegan Sun",
                            ZipCode = "18702"
                        });
                });

            modelBuilder.Entity("ComedyEvents.Models.Event", b =>
                {
                    b.HasOne("ComedyEvents.Models.Venue", "Venue")
                        .WithMany()
                        .HasForeignKey("VenueId");
                });

            modelBuilder.Entity("ComedyEvents.Models.Gig", b =>
                {
                    b.HasOne("ComedyEvents.Models.Comedian", "Comedian")
                        .WithMany()
                        .HasForeignKey("ComedianId");

                    b.HasOne("ComedyEvents.Models.Event", "Event")
                        .WithMany("Gigs")
                        .HasForeignKey("EventId");
                });
#pragma warning restore 612, 618
        }
    }
}
